version: "3"

services:
  db:
    image: postgres:13.9-alpine
    container_name: kube-docker-test-db
    environment:
      - POSTGRES_DB=dtest
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"