version: "3.8"

volumes:
  db_data:
    external: false
  file_data:
    external: false

networks:
  kube-docker-test-net:
    external: false

services:
  app:
    build:
      context: .
      args:
        DEFAULT_PORT: 8888
    container_name: kube-docker-test-app
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/dtest
      - PORT=8888
    ports:
      - "8080:8888"
    depends_on:
      - db
    networks:
      - kube-docker-test-net
    volumes:
      - file_data:/app/user

  db:
    image: postgres:13.9-alpine
    container_name: kube-docker-test-db
    environment:
      - POSTGRES_DB=dtest
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - kube-docker-test-net
    volumes:
      - db_data:/var/lib/postgresql/data