version: "3.8"

volumes:
  db_data:
    external: false
  file_data:
    external: false

# docker-compose uses default group network for all services included (no need to create a specific one)
networks:
  kube-docker-test-net:
    external: false

services:
  app:
    build:
      context: .
      # Set dockerfile name if it differs from "Dockerfile"
      dockerfile: Dockerfile
      args:
        DEFAULT_PORT: 8888
    # By default takes folderName+serviceName
    container_name: kube-docker-test-app
    environment:
      # Alternative way to set env variable
      # DATASOURCE_HOST: db
      - DATASOURCE_HOST=db
      - DATASOURCE_PORT=5432
      - PORT=8888
    # Add environment variables from a file
    # env_file:
    #  - ./.env
    ports:
      - "8080:8888"
    depends_on:
      - db
    networks:
      - kube-docker-test-net
    volumes:
      - file_data:/app/user
    # stdin_open: true (interactive mode)
    # tty: true (attaching mode)

  db:
    image: postgres:13.9-alpine
    container_name: kube-docker-test-db
    environment:
      - POSTGRES_DB=dtest
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - kube-docker-test-net
    volumes:
      - db_data:/var/lib/postgresql/data
    # to local usage
    ports:
      - 5432:5432

  # Utility container
  npm:
    build:
      context: ./node
      dockerfile: NodeUtilityDockerfile
    container_name: kube-docker-test-node
    volumes:
      - ./node:/app
    tty: true
    stdin_open: true