apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  volumeName: db-pv
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""