apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db-pv/
    type: DirectoryOrCreate
  storageClassName: ""