apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  selector:
    app: db-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432